CREATE TABLE voting_session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id   BIGINT    NOT NULL UNIQUE,
    opened_at  TIMESTAMP NOT NULL,
    closes_at  TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_voting_session_topic FOREIGN KEY (topic_id) REFERENCES topic (id)
);