CREATE TABLE vote
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_session_id BIGINT      NOT NULL,
    member_id         VARCHAR(20) NOT NULL,
    choice            VARCHAR(3)  NOT NULL,
    created_at        TIMESTAMP   NOT NULL,
    updated_at        TIMESTAMP   NOT NULL,
    CONSTRAINT fk_vote_session FOREIGN KEY (voting_session_id) REFERENCES voting_session (id),
    CONSTRAINT uk_vote_session_member UNIQUE (voting_session_id, member_id)
);